// Generated by Supabase CLI
// Do not edit manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      data_sources: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          is_active: boolean | null
          last_synced_at: string | null
          name: string
          records_count: number | null
          sync_frequency: string | null
          url: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          last_synced_at?: string | null
          name: string
          records_count?: number | null
          sync_frequency?: string | null
          url?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          last_synced_at?: string | null
          name?: string
          records_count?: number | null
          sync_frequency?: string | null
          url?: string | null
        }
        Relationships: []
      }
      incidents: {
        Row: {
          address: string | null
          av_company: string | null
          city: string | null
          confidence_score: number | null
          created_at: string | null
          description: string | null
          external_id: string | null
          fatalities: number | null
          id: string
          incident_type: string
          injuries: number | null
          latitude: number | null
          location: unknown
          longitude: number | null
          media_urls: Json | null
          occurred_at: string
          raw_data: Json | null
          reported_at: string | null
          reporter_id: string | null
          reporter_type: string | null
          source: string | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          av_company?: string | null
          city?: string | null
          confidence_score?: number | null
          created_at?: string | null
          description?: string | null
          external_id?: string | null
          fatalities?: number | null
          id?: string
          incident_type: string
          injuries?: number | null
          latitude?: number | null
          location: unknown
          longitude?: number | null
          media_urls?: Json | null
          occurred_at: string
          raw_data?: Json | null
          reported_at?: string | null
          reporter_id?: string | null
          reporter_type?: string | null
          source?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          av_company?: string | null
          city?: string | null
          confidence_score?: number | null
          created_at?: string | null
          description?: string | null
          external_id?: string | null
          fatalities?: number | null
          id?: string
          incident_type?: string
          injuries?: number | null
          latitude?: number | null
          location?: unknown
          longitude?: number | null
          media_urls?: Json | null
          occurred_at?: string
          raw_data?: Json | null
          reported_at?: string | null
          reporter_id?: string | null
          reporter_type?: string | null
          source?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      sync_log: {
        Row: {
          completed_at: string | null
          error_message: string | null
          id: string
          metadata: Json | null
          records_created: number | null
          records_processed: number | null
          records_updated: number | null
          source_name: string
          started_at: string | null
          status: string | null
        }
        Insert: {
          completed_at?: string | null
          error_message?: string | null
          id?: string
          metadata?: Json | null
          records_created?: number | null
          records_processed?: number | null
          records_updated?: number | null
          source_name: string
          started_at?: string | null
          status?: string | null
        }
        Update: {
          completed_at?: string | null
          error_message?: string | null
          id?: string
          metadata?: Json | null
          records_created?: number | null
          records_processed?: number | null
          records_updated?: number | null
          source_name?: string
          started_at?: string | null
          status?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      company_stats: {
        Row: {
          av_company: string | null
          blockages: number | null
          collisions: number | null
          earliest_incident: string | null
          latest_incident: string | null
          near_misses: number | null
          sudden_behaviors: number | null
          total_fatalities: number | null
          total_incidents: number | null
          total_injuries: number | null
        }
        Relationships: []
      }
      daily_incident_counts: {
        Row: {
          av_company: string | null
          city: string | null
          date: string | null
          fatalities: number | null
          incident_count: number | null
          incident_type: string | null
          injuries: number | null
        }
        Relationships: []
      }
      incident_stats: {
        Row: {
          blockage_count: number | null
          collision_count: number | null
          cpuc_count: number | null
          cruise_count: number | null
          dmv_count: number | null
          incidents_this_month: number | null
          incidents_this_week: number | null
          last_updated: string | null
          near_miss_count: number | null
          nhtsa_count: number | null
          other_company_count: number | null
          other_type_count: number | null
          sudden_behavior_count: number | null
          tesla_count: number | null
          total_fatalities: number | null
          total_incidents: number | null
          total_injuries: number | null
          user_report_count: number | null
          verified_incidents: number | null
          waymo_count: number | null
          zoox_count: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      refresh_incident_stats: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Views<T extends keyof Database['public']['Views']> = Database['public']['Views'][T]['Row']
export type Insertable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updatable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

